name: Deploy Pabdro
on:
  push:
    branches:
      - 'release/**'
  schedule:
    - cron: '45 19 * * 1'
    - cron: '00 00 * * 1'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy project
        run: echo "Levantando project"
