name: Test Pabdro
on:
  push:
    branches:
      - 'feature/**'
  schedule:
    - cron:  '45 19,0 * * 1' # UTC time
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          npm ci
          npm test
          npm install
