name: Build Pabdro
on:
  push:
    branches:
      - 'feature/**'
  schedule:
    - cron: '45 19 * * 1'
    - cron: '00 00 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: |
          npm ci
          npm run build
